name: Generate Documentation

on:
  push:
    branches: ["**"]
  workflow_dispatch:

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Instala dependencias
        run: |
          python -m pip install --upgrade pip
          pip install sphinx sphinx-rtd-theme pdoc3
          pip install -r requirements.txt

      - name: Genera documentación con pdoc
        run: |
          pdoc --html --output-dir ./docs scrapers utils gadget.py --force

      - name: Despliega a GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
